services:
  database:
    image: postgres:15
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_auth_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: nestdb
    depends_on:
      - database

volumes:
  postgres_data:
